### ISSUE TITLE
How to resize a image dynamically by passing a dynamic width

### ISSUE THREAD

**Issue by kashyap2468** [ikhsanalatsary/multer-sharp-s3#48]
I am trying to set the resizing width from the database values 
I have **successfully developed the function with the Static Width. but doing it dynamic from the database is not possible** 

Can please guide about making the width value dynamic from the database using Helper function.

```
let partsImageResolution = Helper.getResolution();
const uploadS4 = multer({
    storage: s4Storage({
         s3: s3,
        ACL: 'public-read',
        Bucket: 'mxcdn/parts',
        contentType: s4Storage.AUTO_CONTENT_TYPE,
        Key: (req, file, cb) => {
            cb(null, Date.now() + '-' + file.originalname);
        },
        resize: partsImageResolution
    })
}).any();
```

**Comment by ikhsanalatsary** [comment]
@kashyap2468 Since version 0.2.2 you can use `_resize()` but haven't documented it yet. For reference [this](https://github.com/ikhsanalatsary/multer-sharp-s3/blob/c40c1d2ed9ace33df51f1ff079d1fb894c521db3/src/main.ts#L76). In the future I will change the property name to `dynamicResize()`. So for now, let it be working first.
